[package]
name = "interfere-core"
version = "0.1.0"
authors = ["Stef Gijsberts <stefgijsberts@icloud.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.21.0"
num-derive = "0.3.0"
num-traits = "0.2.11"

