[package]
name = "interfere-vst"
version = "0.1.0"
authors = ["Stef Gijsberts <stefgijsberts@icloud.com>"]
edition = "2018"

[dependencies]
interfere-core = { path = "../interfere-core/" }
vst = "0.2.0"
num-traits = "0.2.11"

[lib]
name = "interfere"
crate-type = ["cdylib"]

